import type { UtilityData } from "../utilities-meta";

export const data: UtilityData = {
  intro:
    "Magnetic Ink Character Recognition (MICR) is a 9-digit code printed on the MICR band at the bottom of every Indian cheque. The structure is: first 3 digits — city code (PIN-aligned); next 3 — bank code; last 3 — branch code. MICR enables high-speed cheque processing through the Cheque Truncation System (CTS). With CTS-2010 making cheques near-uniform across banks, MICR remains the routing identifier for paper instruments — but it is no longer used for electronic transfers (NEFT/RTGS/IMPS use IFSC).",
  asOf: "RBI MICR directory — current",
  sections: [
    {
      kind: "table",
      caption: "City code component — major cities (first 3 digits)",
      headers: ["City", "Code"],
      rows: [
        ["Mumbai", "400"],
        ["Delhi", "110"],
        ["Kolkata", "700"],
        ["Chennai", "600"],
        ["Bangalore", "560"],
        ["Hyderabad", "500"],
        ["Ahmedabad", "380"],
        ["Pune", "411"],
        ["Surat", "395"],
        ["Jaipur", "302"],
        ["Lucknow", "226"],
        ["Kanpur", "208"],
        ["Nagpur", "440"],
        ["Indore", "452"],
        ["Bhopal", "462"],
        ["Patna", "800"],
        ["Chandigarh", "160"],
        ["Coimbatore", "641"],
        ["Kochi", "682"],
        ["Vadodara", "390"],
        ["Visakhapatnam", "530"],
        ["Thiruvananthapuram", "695"],
        ["Guwahati", "781"],
        ["Bhubaneswar", "751"],
      ],
      footnote: "City code typically aligns with the first 3 digits of the city's PIN code.",
    },
    {
      kind: "table",
      caption: "Bank code component — major banks (middle 3 digits)",
      headers: ["Bank", "MICR Bank Code"],
      rows: [
        ["State Bank of India", "002"],
        ["Punjab National Bank", "024"],
        ["Bank of Baroda", "012"],
        ["Bank of India", "013"],
        ["Canara Bank", "015"],
        ["Union Bank of India", "018"],
        ["Central Bank of India", "016"],
        ["HDFC Bank", "240"],
        ["ICICI Bank", "229"],
        ["Axis Bank", "211"],
        ["Kotak Mahindra Bank", "485"],
        ["IndusInd Bank", "234"],
        ["Yes Bank", "532"],
        ["IDBI Bank", "259"],
        ["Federal Bank", "049"],
        ["RBL Bank", "267"],
        ["Standard Chartered", "036"],
        ["Citibank", "037"],
      ],
      footnote: "Branch code (last 3 digits) is unique to each branch — refer to the cheque book or the RBI master to identify a specific branch.",
    },
    {
      kind: "external",
      title: "Find any MICR code",
      body: [
        "The full MICR master is published by RBI alongside the IFSC directory. Your printed cheque book is the simplest source — the 9-digit MICR sits between the cheque number and the account number on the bottom band.",
      ],
      links: [
        { label: "RBI — IFSC & MICR Details (official)", href: "https://www.rbi.org.in/scripts/IFSCMICRDetails.aspx" },
        { label: "Razorpay IFSC & MICR Toolkit", href: "https://razorpay.com/ifsc/" },
      ],
    },
    {
      kind: "note",
      title: "MICR vs IFSC — when does which apply",
      body: [
        "MICR — used for cheque clearing under CTS. Printed on the cheque band.",
        "IFSC — used for electronic transfers (NEFT, RTGS, IMPS, UPI back-end routing).",
        "Both codes coexist for every bank branch. MICR is still required for cheque deposits but is irrelevant for online transfers.",
      ],
    },
  ],
};
