import type { UtilityData } from "../utilities-meta";

export const data: UtilityData = {
  intro:
    "The National Industrial Classification (NIC-2008) is the standard activity classification used in MCA filings (SPICe+, AOC-4, MGT-7), GST registration, and most government regulatory forms. It harmonises with the UN's ISIC Rev. 4. Companies must select the most specific 5-digit code that describes the principal business activity — and where multiple activities are conducted, list them in order of revenue contribution. NIC-2008 is structured as: Section (alphabet) → Division (2-digit) → Group (3-digit) → Class (4-digit) → Sub-class (5-digit).",
  asOf: "Ministry of Statistics & Programme Implementation — NIC-2008",
  sections: [
    {
      kind: "table",
      caption: "NIC-2008 — Sections (top-level)",
      headers: ["Section", "Description", "Divisions"],
      rows: [
        ["A", "Agriculture, forestry and fishing", "01–03"],
        ["B", "Mining and quarrying", "05–09"],
        ["C", "Manufacturing", "10–33"],
        ["D", "Electricity, gas, steam and air conditioning supply", "35"],
        ["E", "Water supply; sewerage, waste management and remediation", "36–39"],
        ["F", "Construction", "41–43"],
        ["G", "Wholesale and retail trade; repair of motor vehicles", "45–47"],
        ["H", "Transportation and storage", "49–53"],
        ["I", "Accommodation and Food service activities", "55–56"],
        ["J", "Information and communication", "58–63"],
        ["K", "Financial and insurance activities", "64–66"],
        ["L", "Real estate activities", "68"],
        ["M", "Professional, scientific and technical activities", "69–75"],
        ["N", "Administrative and support service activities", "77–82"],
        ["O", "Public administration and defence", "84"],
        ["P", "Education", "85"],
        ["Q", "Human health and social work activities", "86–88"],
        ["R", "Arts, entertainment and recreation", "90–93"],
        ["S", "Other service activities", "94–96"],
        ["T", "Activities of households as employers", "97–98"],
        ["U", "Activities of extraterritorial organisations and bodies", "99"],
      ],
    },
    {
      kind: "table",
      caption: "Commonly used class codes — first 3 digits of frequently filed activities",
      headers: ["Code", "Activity"],
      rows: [
        ["010", "Crop and animal production"],
        ["011", "Growing of non-perennial crops"],
        ["014", "Animal production"],
        ["101", "Processing and preserving of meat"],
        ["106", "Manufacture of grain mill products, starches"],
        ["131", "Spinning, weaving and finishing of textiles"],
        ["141", "Manufacture of wearing apparel"],
        ["201", "Manufacture of basic chemicals, fertilisers, plastics"],
        ["210", "Manufacture of pharmaceuticals, medicinal chemicals"],
        ["241", "Manufacture of basic iron and steel"],
        ["261", "Manufacture of electronic components"],
        ["292", "Manufacture of bodies for motor vehicles, trailers"],
        ["410", "Construction of buildings"],
        ["421", "Construction of roads and railways"],
        ["452", "Maintenance and repair of motor vehicles"],
        ["461", "Wholesale on a fee or contract basis"],
        ["471", "Retail sale in non-specialised stores"],
        ["472", "Retail sale of food, beverages, tobacco in specialised stores"],
        ["491", "Transport via railways"],
        ["493", "Other land transport (incl. road freight)"],
        ["551", "Short-term accommodation (hotels)"],
        ["561", "Restaurants and mobile food service"],
        ["581", "Publishing of books, periodicals"],
        ["620", "Computer programming, consultancy"],
        ["631", "Data processing, hosting and related activities"],
        ["641", "Monetary intermediation (banks)"],
        ["651", "Insurance"],
        ["681", "Real estate — own/leased property"],
        ["682", "Real estate — on fee or contract basis"],
        ["691", "Legal activities"],
        ["692", "Accounting, book-keeping, auditing; tax consultancy"],
        ["702", "Management consultancy activities"],
        ["711", "Architectural and engineering activities; technical testing"],
        ["749", "Other professional, scientific and technical activities"],
        ["821", "Office administrative and support activities"],
        ["851", "Pre-primary and primary education"],
        ["854", "Higher education"],
        ["861", "Hospital activities"],
        ["862", "Medical and dental practice activities"],
      ],
    },
    {
      kind: "external",
      title: "Full NIC-2008 directory",
      body: [
        "MCA publishes the full NIC-2008 codes (down to 5-digit sub-class level) for use in SPICe+, AOC-4 and INC-20A. MoSPI maintains the canonical version.",
      ],
      links: [
        { label: "MCA — NIC-2008 directory (full)", href: "https://www.mca.gov.in/MinistryV2/nic_2008.html" },
        { label: "MoSPI — NIC-2008 official", href: "https://mospi.gov.in/national-industrial-classification" },
      ],
    },
    {
      kind: "note",
      title: "Practical tips",
      body: [
        "Always pick the 5-digit code that maps to the actual principal activity. Generic 'wholesale trade' or 'consulting' classifications attract additional scrutiny in MCA Form INC-20A (commencement of business).",
        "For multi-activity companies, list activities in descending order of revenue contribution. A change in NIC code post-incorporation requires a board resolution and MGT-14 filing.",
        "GST registration uses HSN/SAC for goods/services but NIC for the 'principal place of business' activity descriptor — the two must be aligned.",
      ],
    },
  ],
};
